[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solora = "DfPLBwWW72YKYt81eVUznE1amapTtXroFGTdGqHo1Ttf"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[hooks]
