[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solora = "8tkBctMGe5CsGQ731t9di9hBjGg7rbMo4VEk8WujvTPS"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[hooks]
